services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    restart: always
    environment:
      PMA_HOST: mysql-container
      PMA_USER: user
      PMA_PASSWORD: password
    ports:
      - "8081:80"
    networks:
      - my-network

networks:
  my-network:
    external: true
